{% set name = "pyreadstat" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3c9f0feae62a5dbbdd38b818b20bec291e37f396831fbd2435735ca3a241031f

build:
  number: 0
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler("m2w64_c") }}  # [win]
    - {{ compiler('c') }}  # [not win]
  host:
    - python
    - pip
    - cython
    - m2w64-toolchain  # [win]
    - libpython  # [win]
    - zlib  # [not win]
  run:
    - python
    - pandas
    - m2w64-gcc-libs  # [win]
    - zlib  # [not win]

test:
  imports:
    - pyreadstat

about:
  home: https://github.com/Roche/pyreadstat
  license: Apache
  license_family: Apache
  license_file: LICENSE.txt
  summary: read SAS, SPSS and STATA files into pandas data frames
  description: |
    A Python package to read SAS (sas7bdat, sas7bcat, xport/xpt), SPSS (sav, zsav, por) and Stata (dta) files into pandas data frames. It is a wrapper around the C library readstat.
  doc_url: https://github.com/Roche/pyreadstat
  dev_url: https://github.com/Roche/pyreadstat

extra:
  recipe-maintainers:
    - ofajardo
