{% set name = "pyreadstat" %}
{% set version = "1.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bc2142be4773a9e7ff844068d0b48c413f9f46ba9511408bcd5dbec9b20aab6d

build:
  number: 0
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}  # [win]
    - {{ compiler('c') }}  # [not win]
  c_stdlib:
    - sysroot                    # [linux]
    - macosx_deployment_target   # [osx]
    - vs                         # [win]
  c_stdlib_version:              # [unix]
    - 2.12                       # [linux and x86_64]
    - 2.17                       # [linux and not x86_64]
    - 10.9                       # [osx and x86_64]
    - 11.0                       # [osx and arm64]
  host:
    - python
    - pip
    - cython
    - setuptools
    - zlib  # [not win]
    - zlib  # [win]
    - libiconv  # [win]
  run:
    - python
    - pandas
    - zlib  # [not win]
    - zlib  # [win]
    - libiconv  # [win]

test:
  imports:
    - pyreadstat

about:
  home: https://github.com/Roche/pyreadstat
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: read SAS, SPSS and STATA files into pandas data frames
  description: |
    A Python package to read SAS (sas7bdat, sas7bcat, xport/xpt), SPSS (sav, zsav, por) and Stata (dta) files into pandas data frames. It is a wrapper around the C library readstat.
  doc_url: https://github.com/Roche/pyreadstat
  dev_url: https://github.com/Roche/pyreadstat

extra:
  recipe-maintainers:
    - ofajardo
